// Copyright (C) 2026 AnalyseDeCircuit
// SPDX-License-Identifier: GPL-3.0-only

/// User-facing labels copied from Tauri `src/locales/*/ide.json`.
///
/// The GPUI app can replace these with its i18n loader. English defaults keep
/// the crate testable without depending on the app-level locale crate.
#[derive(Clone, Debug)]
pub struct IdeLabels {
    pub file_too_large: String,
    pub file_encoding: String,
    pub file_line_ending: String,
    pub reopen_encoding: String,
    pub save_encoding: String,
    pub reopen_dirty: String,
    pub invalid_encoding: String,
    pub unrepresentable_text: String,
    pub large_file: String,

    pub open_folder: String,
    pub search: String,
    pub refresh: String,
    pub search_placeholder: String,
    pub search_hint: String,
    pub searching: String,
    pub no_results: String,
    pub search_truncated: String,
    pub search_results_count: String,
    pub select_folder: String,
    pub select_folder_desc: String,
    pub go: String,
    pub go_to_parent: String,
    pub no_subfolders: String,
    pub selected_path: String,
    pub loading_project: String,
    pub open_failed: String,
    pub retry: String,
    pub disconnected_overlay: String,
    pub no_project: String,
    pub no_open_files: String,
    pub click_to_open: String,
    pub loading_file: String,
    pub save_failed: String,
    pub conflict_title: String,
    pub conflict_desc: String,
    pub your_version: String,
    pub remote_version: String,
    pub reload_remote: String,
    pub overwrite: String,
    pub unsaved_changes: String,
    pub unsaved_changes_folder: String,
    pub unsaved_changes_desc: String,
    pub save: String,
    pub discard: String,
    pub cancel: String,
    pub find_placeholder: String,
    pub replace_placeholder: String,
    pub find_next: String,
    pub find_previous: String,
    pub match_case: String,
    pub toggle_replace: String,
    pub close_search: String,
    pub replace_btn: String,
    pub replace_all_btn: String,
    pub replace: String,
    pub replace_all: String,
    pub editor_copy: String,
    pub editor_cut: String,
    pub editor_paste: String,
    pub editor_select_all: String,
    pub pin_tab: String,
    pub unpin_tab: String,
    pub close_tab: String,
    pub context_new_file: String,
    pub context_new_folder: String,
    pub context_rename: String,
    pub context_delete: String,
    pub context_copy: String,
    pub context_cut: String,
    pub context_paste: String,
    pub context_copy_path: String,
    pub context_open_in_terminal: String,
    pub new_file_placeholder: String,
    pub new_folder_placeholder: String,
    pub validation_name_empty: String,
    pub validation_name_contains_slash: String,
    pub validation_name_invalid: String,
    pub validation_name_invalid_chars: String,
    pub validation_name_too_long: String,
    pub delete_confirm_title: String,
    pub delete_folder_warning: String,
    pub delete_will_close_tabs: String,
    pub delete_has_unsaved: String,
    pub delete_confirm: String,
    pub delete_deleting: String,
    pub sftp_mode: String,
    pub agent_ready: String,
    pub agent_deploying: String,
    pub agent_checking: String,
    pub agent_manual_upload: String,
    pub agent_manual_update: String,
    pub agent_optin_title: String,
    pub agent_optin_desc: String,
    pub agent_optin_benefit_watch: String,
    pub agent_optin_benefit_git: String,
    pub agent_optin_benefit_atomic: String,
    pub agent_optin_remember: String,
    pub agent_optin_sftp_only: String,
    pub agent_optin_enable: String,
    pub agent_remove_btn: String,
    pub agent_deploy_btn: String,
    pub agent_remove_confirm_title: String,
    pub agent_remove_confirm_desc: String,
    pub agent_remove_confirm_btn: String,
    pub agent_manual_upload_hint: String,
    pub agent_manual_update_hint: String,
    pub agent_download_link: String,
    pub agent_upload_to: String,
    pub agent_manual_upload_arch: String,
    pub agent_manual_update_current_agent_version: String,
    pub agent_manual_update_current_compatibility_version: String,
    pub agent_manual_update_expected_compatibility_version: String,
    pub agent_retry_btn: String,
}

impl Default for IdeLabels {
    fn default() -> Self {
        Self {
            file_too_large: "The file exceeds the 100 MiB IDE editing limit.".into(),
            file_encoding: "File encoding".into(),
            file_line_ending: "Line endings".into(),
            reopen_encoding: "Reopen with encoding".into(),
            save_encoding: "Save with encoding".into(),
            reopen_dirty: "Save or discard changes before reopening with another encoding.".into(),
            invalid_encoding: "Cannot decode this file with the selected encoding.".into(),
            unrepresentable_text: "This encoding cannot represent all characters. Choose UTF-8 to save without losing text.".into(),
            large_file: "Large file: syntax and wrapping off".into(),

            open_folder: "Open Folder".into(),
            search: "Search".into(),
            refresh: "Refresh".into(),
            search_placeholder: "Search file contents...".into(),
            search_hint: "Enter keywords to search".into(),
            searching: "Searching...".into(),
            no_results: "No results found".into(),
            search_truncated:
                "Results truncated. Refine your search for more specific matches.".into(),
            search_results_count: "{{count}} results in {{files}} files".into(),
            select_folder: "Select Folder".into(),
            select_folder_desc: "Select a remote folder to open".into(),
            go: "Go".into(),
            go_to_parent: "Go to parent directory".into(),
            no_subfolders: "No subfolders".into(),
            selected_path: "Selected path".into(),
            loading_project: "Loading project...".into(),
            open_failed: "Failed to open project".into(),
            retry: "Retry".into(),
            disconnected_overlay: "Connection lost. Reconnecting...".into(),
            no_project: "No project open".into(),
            no_open_files: "No open files".into(),
            click_to_open: "Click a file in the tree to open it".into(),
            loading_file: "Loading file...".into(),
            save_failed: "Save failed".into(),
            conflict_title: "File modified".into(),
            conflict_desc: "\"{{fileName}}\" has been modified on the remote server since you opened it.".into(),
            your_version: "Your version".into(),
            remote_version: "Remote version".into(),
            reload_remote: "Reload remote version".into(),
            overwrite: "Overwrite remote version".into(),
            unsaved_changes: "Unsaved Changes".into(),
            unsaved_changes_folder:
                "You have unsaved changes. Switching folders will discard them. Continue?".into(),
            unsaved_changes_desc: "Do you want to save the changes to {{fileName}}?".into(),
            save: "Save".into(),
            discard: "Discard".into(),
            cancel: "Cancel".into(),
            find_placeholder: "Find".into(),
            replace_placeholder: "Replace".into(),
            find_next: "Next match (Enter)".into(),
            find_previous: "Previous match (Shift+Enter)".into(),
            match_case: "Match case".into(),
            toggle_replace: "Toggle replace".into(),
            close_search: "Close search (Esc)".into(),
            replace_btn: "Replace".into(),
            replace_all_btn: "All".into(),
            replace: "Replace current".into(),
            replace_all: "Replace all".into(),
            editor_copy: "Copy".into(),
            editor_cut: "Cut".into(),
            editor_paste: "Paste".into(),
            editor_select_all: "Select All".into(),
            pin_tab: "Pin".into(),
            unpin_tab: "Unpin".into(),
            close_tab: "Close".into(),
            context_new_file: "New File".into(),
            context_new_folder: "New Folder".into(),
            context_rename: "Rename".into(),
            context_delete: "Delete".into(),
            context_copy: "Copy".into(),
            context_cut: "Cut".into(),
            context_paste: "Paste".into(),
            context_copy_path: "Copy Path".into(),
            context_open_in_terminal: "Open in Terminal".into(),
            new_file_placeholder: "filename.ext".into(),
            new_folder_placeholder: "folder name".into(),
            validation_name_empty: "Name cannot be empty".into(),
            validation_name_contains_slash: "Name cannot contain /".into(),
            validation_name_invalid: "Invalid name".into(),
            validation_name_invalid_chars: "Name contains invalid characters".into(),
            validation_name_too_long: "Name is too long".into(),
            delete_confirm_title: "Confirm Delete".into(),
            delete_folder_warning:
                "This will permanently delete all contents inside the folder.".into(),
            delete_will_close_tabs: "{{count}} open tab(s) will be closed.".into(),
            delete_has_unsaved:
                "Cannot delete: {{count}} file(s) have unsaved changes. Save or discard changes first.".into(),
            delete_confirm: "Delete".into(),
            delete_deleting: "Deleting...".into(),
            sftp_mode: "SFTP".into(),
            agent_ready: "Agent active".into(),
            agent_deploying: "Deploying agent...".into(),
            agent_checking: "Checking agent...".into(),
            agent_manual_upload: "Manual upload required".into(),
            agent_manual_update: "Manual update required".into(),
            agent_optin_title: "Enable Remote Agent?".into(),
            agent_optin_desc: "RayTerm can deploy a lightweight agent (~2 MB) to the remote host for enhanced IDE features. The agent runs inside your existing SSH connection and makes no external network calls.".into(),
            agent_optin_benefit_watch:
                "Real-time file watching (instant tree refresh on external changes)".into(),
            agent_optin_benefit_git: "Native Git status integration".into(),
            agent_optin_benefit_atomic:
                "Atomic file writes with hash-based conflict detection".into(),
            agent_optin_remember: "Don't ask again".into(),
            agent_optin_sftp_only: "SFTP Only".into(),
            agent_optin_enable: "Enable Agent".into(),
            agent_remove_btn: "Remove Agent".into(),
            agent_deploy_btn: "Deploy Agent".into(),
            agent_remove_confirm_title: "Remove Remote Agent?".into(),
            agent_remove_confirm_desc: "This will stop the agent process and delete the binary from the remote host. IDE mode will fall back to SFTP.".into(),
            agent_remove_confirm_btn: "Remove".into(),
            agent_manual_upload_hint: "Unsupported architecture. Build the agent from source and upload it to the remote host.".into(),
            agent_manual_update_hint:
                "An incompatible agent was found. Build a compatible version and replace the remote file.".into(),
            agent_download_link: "Build instructions".into(),
            agent_upload_to: "Upload to:".into(),
            agent_manual_upload_arch: "Architecture: {{arch}}".into(),
            agent_manual_update_current_agent_version: "Agent version: {{version}}".into(),
            agent_manual_update_current_compatibility_version:
                "Compatibility version: {{version}}".into(),
            agent_manual_update_expected_compatibility_version:
                "Required compatibility version: {{version}}".into(),
            agent_retry_btn: "Retry Deploy".into(),
        }
    }
}

impl IdeLabels {
    pub(crate) fn tree_name_validation_message(&self, key_or_message: &str) -> String {
        match key_or_message {
            "ide.validation.nameEmpty" => self.validation_name_empty.clone(),
            "ide.validation.nameContainsSlash" => self.validation_name_contains_slash.clone(),
            "ide.validation.nameInvalid" => self.validation_name_invalid.clone(),
            "ide.validation.nameInvalidChars" => self.validation_name_invalid_chars.clone(),
            "ide.validation.nameTooLong" => self.validation_name_too_long.clone(),
            // Backend errors are already user-facing messages rather than i18n keys.
            message => message.to_string(),
        }
    }
}
